##The website title
name: Stevão Andrade
##Markdown processor
markdown: kramdown

##syntax highlighter. change it to pygments
##highlighter: pygments do not suported in github pages, change to rouge

rouge: pygments

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: /site
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"

##Fix pagination problem after update jekyll to 3.0 version
gems: [jekyll-paginate]

##The website description (to be used in meta tags)
description: This blog will be used to share some informations about my researchs
##Some frequently used keywords on your website
keywords: software engineering, software testing, mutation testing

##define this for disqus comment support
#disqus: forumname

##set this to enable google analytics
ga_id: analyticsID
ga_domain: analyticsDomain

##Some commonly used links
links:
  facebook: stevao.andrade
  twitter: stevao_andrade
  email: stevao.andrade@gmail.com
  github: stevao-andrade
  instagram: stevao_andrade

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: placeholder.jpg
##comment this if you want full width posts with no sidebar
sidebar: on


